apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
spec:
  selector:
    app: pagamentos
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002
  type: NodePort
