name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install --no-audit --no-fund

      - name: Checar formatação
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Testes automatizados
        run: npm test

      - name: Build do projeto
        run: npm run build

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push - Pedidos
        uses: docker/build-push-action@v4
        with:
          context: ./src/pedidos
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pedidos:latest

      - name: Build e Push - Pagamentos
        uses: docker/build-push-action@v4
        with:
          context: ./src/pagamentos
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pagamentos:latest

      - name: Build e Push - Estoque
        uses: docker/build-push-action@v4
        with:
          context: ./src/estoque
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/estoque:latest
